apiVersion: v1
kind: Pod
metadata:
  name: u16con
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: ubuntu16-con
    image: ubuntu:16.04
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure
