apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-gcp-volume
spec:
  containers:
  - name: nginx-pod-gcp-volume
    image: nginx
    ports:
      - name: nginx-port
        containerPort: 80
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/creds
      readOnly: true
    - name: gcp-volume
      mountPath: /tmp
  volumes:
  - name: secret-volume
    secret:
      secretName: demo-secret
  - name: gcp-volume
    persistentVolumeClaim:
      claimName: my-readonly-pvc
