apiVersion: v1
kind: Pod
metadata:
  name: nginx-security
spec:
  containers:
  - name: nginx-pod-gcp-volume
    image: nginx
    ports:
      - name: nginx-port
        containerPort: 80
    env:
    - name: SECRET_DEMO_USERNAME
      valueFrom:
        secretKeyRef:
          name: demo-secret
          key: username
    - name: SECRET_DEMO_PASSWORD
      valueFrom:
        secretKeyRef:
          name: demo-secret
          key: password
# volumes:
#  - name: demo-secret
#    secret:
#      secretName: demo-secret
