kind: Service
apiVersion: v1
metadata:
  name: databases-service
  labels: 
    app: databases
spec:
  type: NodePort
  selector:
    app: databases
  ports:
    - name: http
      protocol: TCP
      port: 3306
#      targetPort: 80
#      nodePort: 30060
#  externalIPs:
#  - 10.50.1.60
