apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: databases
spec:
  selector:
    matchLabels:
      app: databases
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: databases
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-nfs-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-nfs-storage
        nfs:
         server: 10.50.1.51
         path: /k8sNFS
   
