apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.1"
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: storage
          mountPath: /tmp
      - name: python
        image: demoyuw/python-flask:v0.3-alpine
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 10009
        volumeMounts:
        - mountPath: /tmp
          name: storage
      volumes:
      - name: storage
        emptyDir: {}
#        nfs:
#         server: 10.50.1.51
#         path: /k8sNFS
#      - name: python-nfs-storage
#        nfs:
#         server: 10.50.1.51
#         path: /k8sNFS-python
   
