apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: python
spec:
  selector:
    matchLabels:
      app: python
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: python
    spec:
      replicas: 1
      containers:
      - name: python
        image: demoyuw/python-flask:v0.3-alpine
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1280Mi"
            cpu: "5000m"
        ports:
        - containerPort: 10009
        volumeMounts:
        - mountPath: /var/lib/python
          name: python-nfs-storage
      volumes:
      - name: python-nfs-storage
        nfs:
         server: 10.50.1.51
         path: /k8sNFS-python
   
