kind: Service
apiVersion: v1
metadata:
  name: php-apache
  labels: 
    app: php-apache
spec:
  type: NodePort
  selector:
    app: php-apache
  ports:
    - name: http
      protocol: TCP
      port: 80
